### PR TITLE
Verified that there are no issues with springfox

### PR DESCRIPTION
**Pull request by dilipkrish**
@oeresundsgruppen It appears you have a custom IDE specific configuration and launching the war with eclipse specific settings will not work the way springboot is intended to work.

I verified everything is working as expected and updated the instructions in the README.

### CODE REVIEW

**Comment by oeresundsgruppen** [comment]
Thanks, have been running this mostly in tomcat without eclipse. pom-file refers to v2.9, which is not in maven, and if I downgrade to 2.8, I get exceptions at startup (Failed to introspect Class), with the maven install... Might require 2.9 ?

**Comment by dilipkrish** [comment]
Not sure I didnt try with 2.8. 

You keep saying its not available in maven 😕 .... its a matter of adding a different repository, either using this example [in your settings.xml](https://stackoverflow.com/a/44304245/19219) or adding the repository [inlined in your pom file](https://www.mkyong.com/maven/how-to-add-remote-repository-in-maven-pom-xml/). 2.9.1 should be available, until then this should get you going.

**Comment by oeresundsgruppen** [comment]
Pointing to central then works a bit, but gives: [ERROR] Failed to execute goal on project swaggerTest: Could not resolve dependencies for project swaggerTest:swaggerTest:war:1.0: The following artifacts could not be resolved: io.springfox:springfox-swagger2:jar:2.9.1, io.springfox:springfox-swagger-ui:jar:2.9.1: Could not find artifact io.springfox:springfox-swagger2:jar:2.9.1 in central (http://jcenter.bintray.com) -> [Help 1], i will look more tomorrow

**Comment by oeresundsgruppen** [comment]
It is still not in Maven, 2.9 nor 2.9.1 - any ETA please ?

**Comment by dan-kirberger** [comment]
As he said, its not in **maven central**, it is in jcenter however. So you can add jcenter to your pom/build.gradle as a repository.

**Comment by oeresundsgruppen** [comment]
yes, but dont really want to switch my builds to jcenter just for springfox. 2.9.1. is in neither maven repo or jcenter...

**Comment by oeresundsgruppen** [comment]
So if you were to describe the changes you did... You move the source to main/java, as this appears to be more standard. Which change makes the difference ?

**Comment by oeresundsgruppen** [comment]
Hi Dilip, this still does not work if deployed under tomcat, which web-server do you use ?

**Comment by oeresundsgruppen** [comment]
actually neither works running as spring-boot:run, as you have broken the rest-call (webAPI does not work), to get the swagger stuff to show. Both needs to work. I would suggest that you fix swagger, to actually work as is, and not to break app code - make sense ?

**Comment by oeresundsgruppen** [comment]
When deployed to tomcat, the application will show under /swaggerTest, e.g. /swaggerTest/webAPI will show OK, and /swaggerTest/v2/api-docs will show nothing and /swaggerTest/swagger-ui.html will show the famous swagger-bug = UNABLE TO INFER BASE HOST.....

**Comment by oeresundsgruppen** [comment]
please fix this, been outstanding for months now....

**Comment by dilipkrish** [comment]
@oeresundsgruppen As my PR demonstrated its not really an issue with springfox. Its how you're packaging/deploying/running that is an issue. 

> So if you were to describe the changes you did... You move the source to main/java, as this appears to be more standard. Which change makes the difference ?

The main change I made is to use the maven spring-boot plugin to run the application. This is because I'm assuming this is a spring boot application given your dependencies. This is so that I/we have a standard way to deploy/run/test the application. 

I noted the gaps ___you___ need to figure out in the README. Just for clarity I'm going to repeat here as well. 
- You need to use the spring boot mechanism to [package as a war](https://spring.io/guides/gs/convert-jar-to-war/) before trying to deploy on a standard container.
- If you want to run locally you can use spring-boot:run to run it locally
- `http://localhost:8080/swagger-ui.html` shows the endpoints you expect to see. Also executing the endpoint using the "Try it out" action, works as expected failing at the point it tries to resolve the response from your endpoint "OK"
- You need to change the way you package your `WebContent` for spring boot to be able to resove `OK.jsp`. I'm _NOT_ going to try and figure that for you.

Just to re-iterate, this is not a problem with the library. The library is only responsible for generating the api specification which is adequately demonstrated by navigating to `http://localhost:8080/v2/api-docs`. The swagger-ui library is just a convenience offered for __STANDARD__ deployment. Anything outside of that needing custom configuration the bundled swagger-ui is not an option nor supported.

**Comment by oeresundsgruppen** [comment]
springfox is broken, soo many developers have experienced - UNABLE TO INFER BASE HOST - and you just ignore them...

**Comment by oeresundsgruppen** [comment]
try to run it in a tomcat web server or deploy it to aws, alibaba, heroku, google - your choice, swagger foxs is broken

**Comment by oeresundsgruppen** [comment]
spring-boot:run is not how apps are deployed btw, so please step out into reality and the real world

**Comment by oeresundsgruppen** [comment]
Tried with latest and greatest 2.9.2 and still same problem, ever going to fix this ?

**Comment by dilipkrish** [comment]
Fix what exactly? As I mentioned [earlier](https://github.com/oeresundsgruppen/swaggerTest/pull/1#issuecomment-397880238) ☝️and demonstrated in the PR, this is a deployment and packaging issue that is unrelated to springfox. If you're able to navigate to `http://localhost:8080/v2/api-docs` and see the service description, there is no issue with springfox.

**Comment by oeresundsgruppen** [comment]
Noone uses springboot-run to deploy apps, deploy it in ANY web-server, and you will see the error, that many developers are reporting: UNABLE TO INFER BASE HOST.

**Comment by dilipkrish** [comment]
No one is expecting that you run `spring-boot:run` in production. However I do expect that you build and run the jar/war in a standard way. Either one of these works
- you run a boot application like it should either `java -jar boot-application.jar`
- or if you want to [package it as a war](https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#howto-create-a-deployable-war-file) you can do that pretty easily.

Secondly many developers are reporting `unable to infer base host` because it is a very environment specific problem and cannot be dealt with systemically. Some of the common reasons for those are
- You are running in a load balanced environment or are fronted by an api gateway. If thats the case you need to set up the x-forward headers correctly and enable that behavior in spring boot.
- If you are running a boot app but elected to configure the web application yourself, either by `@EnableWebMvc` annotation or implementing `WebMvcConfigurationSupport`, then you need to configure your swagger-ui on your own. The web jar will not be auto configured for you
- Lastly, If your running into this issue because you have configured your servlet incorrectly, that is not easy to figure out as a library. 

In your case I believe its the last scenario. Hand-rolling a war file with a [`WebContent` folder](https://github.com/oeresundsgruppen/swaggerTest/tree/master/WebContent/WEB-INF) so that it can run in your IDE and not being able to infer the base url, is really not an problem with springfox. To give you an analogy, its like saying, I configured the datasource connection url incorrectly and chose to expect hibernate to fix the problem of not being able to connect to the database.

While I can help you figure out the problem as much as I can, I don't have the bandwidth to support each and every one with similar problems.

Hope that helps.

**Comment by oeresundsgruppen** [comment]
The example I made for you, is a WAR-deployment in the maven. And it 
contains everything for you to see, why folks get the unable to infer 
base bug. The example comes with WebMvcConfigurerAdapter and 
WebSecurityConfigurerAdapter, which allows for various hacks, which you 
known best of all, yet you change nothing here...

Which alternative would you recommend, if this cannot be fixed ?

**Comment by oeresundsgruppen** [comment]
19:01:28.528 WARN [http-nio-8080-exec-7] org.springframework.web.servlet.PageNotFound - No mapping found for HTTP request with URI [/null/swagger-resources/configuration/security] in DispatcherServlet with name 'dispatcherServlet'

the null is a bug in your code....

**Comment by oeresundsgruppen** [comment]
The example makes a WAR, which can be deployed into Tomcat. 

spring-boot:runs has many issues with jsps, so that is a no-go currently.

**Pull request merged**
